
from collections import defaultdict
import pandas as pd

def get_categories():

        # Sample organization logic
    word_lists = {
        "animals": [
            "aardvark", "alligator", "ant", "anteater", "antelope", "alpaca", "badger", "bat1", "bear", "beaver", "bee", 
            "beetle", "bison", "boar", "buffalo", "bull", "butterfly", "camel", "cat", "caterpillar", "catfish", "chameleon", 
            "cheetah", "chicken2", "chimpanzee", "chipmunk", "chinchilla", "cockroach", "cow", "coyote", 
            "crab", "crayfish", "crow", "deer", "dog", "dolphin", "donkey", "duck", "duckling", "eagle", "eel", "elephant", 
            "ferret", "fish", "fox", "frog", "gazelle", "giraffe", "goat", "goldfish", "goose", "gorilla", "groundhog", 
            "guinea_pig", "hamster", "hawk", "hedgehog", "hippopotamus", "horse", "hummingbird", "hyena", "iguana", "jellyfish", 
            "kangaroo", "kitten", "koala", "lamb", "lemur", "leopard", "lion", "lizard", "llama", "lobster", "manatee", "meerkat", 
            "mole", "mongoose", "monkey", "moose", "mosquito", "mouse1", "mule", "octopus", "orangutan", "ostrich", 
            "otter", "owl", "oyster", "panda", "panther", "parrot", "peacock", "pelican", "penguin", "pheasant", "pig", 
            "pigeon", "platypus", "polar_bear", "pony", "porcupine", "possum", "prawn", "puppy", "rabbit", "raccoon", 
            "ram", "rat", "rattlesnake", "reindeer", "rhinoceros", "rooster", "salamander", "salmon", "scorpion", "seal", 
            "shark", "sheep", "skunk", "sloth", "slug", "snail", "snake", "spider", "squid", "squirrel", "starfish", 
            "stingray", "swan", "tadpole", "tiger", "toad", "tortoise", "turkey", "turtle", "walrus", "wasp", "weasel", 
            "whale", "wolf", "wombat", "worm", "yak", "zebra", 'beehive','bird', 'blowfish','bug','fishbowl','cardinal',
            'earwig',"octopus","barnacle", 

            "calf1",  "chick",  "chihuahua",  "cobra",  "cockatoo",  "cocoon",  "coral",
            "cougar",  "dalmatian",  "dragonfly",  "flamingo",  "fly",  "gopher",  "grasshopper",
            "ladybug",  "leech",  "lightning_bug",  "maggot",  "moth",  "mussel",  "nest",  "piglet",
            "poodle",  "praying_mantis",  "puffin",  "pug",  "racehorse",  "sea_urchin",  "seagull",  "seahorse",
            "spider_web",  "swordfish",  "tarantula",  "tick",  "toucan",  "vulture",  "warthog",  "fossil",
            "buffet",
        ],
        
        "foods_and_plants": [
            "acorn", "almond", "aloe", "apple", "apple_tree", "applesauce", "artichoke", "arugula", "asparagus", 
            "avocado", "bacon", "bagel", "baklava", "banana", "banana_peel", "banana_split", "basil", "bean", 
            "beet", "bell_pepper", "berry", "biscuit", "blackberry", "blueberry", "bok_choy", "bologna", "broccoli", 
            "brownie", "brussels_sprouts", "bun", "burrito", "butter", "cake", "calamari", "candy", "candy_bar", 
            "candy_cane", "caramel", "carrot", "cashew", "cauliflower", "caviar", "celery", "cheese", "cheeseburger", 
            "cheesecake", "cherry", "chicken1", "chickpea", "chili", "chive", "chocolate", "clam","coconut", "coffee", "cookie", 
            "cranberry", "cream", "cream_cheese", "creme_brulee", "crepe", "croissant", "cucumber", "cupcake", 
            "curry", "dough", "dumpling", "egg", "egg_roll", "eggnog", "eggplant", "fennel", "fig", 
            "flan", "flour", "fondue", "french_fries", "fruit", "fruitcake", "fudge", "garlic", "ginger", "gingerbread_man", 
            "grape", "grapefruit", "guacamole", "hamburger", "honey", "hot_chocolate", "hotdog", "ice_cream", "jam", 
            "jelly_bean", "juice", "kale", "kebab", "ketchup", "kiwi", "lasagna", "leek", "lemon", "lemonade", "lettuce", 
            "licorice", "lime", "macadamia", "macaroni", "mango", "maple_syrup", "marshmallow", "mashed_potato", 
            "mayonnaise", "meat", "meatball", "meatloaf", "melon", "milk", "milkshake", "mint", "mousse", "muffin", 
            "mushroom", "nacho", "noodle", "nut", "oatmeal", "okra", "olive", "omelet", "onion", "orange", 
            "papaya", "parsley", "pasta", "pastry", "peach", "peanut", "pear", "pecan", "pepperoni", "pie", "pizza", 
            "plum", "pomegranate", "popcorn", "popsicle", "potato", "pretzel", "pumpkin", "quiche", "radish", 
            "raisin", "raspberry", "ravioli", "rice", "salad", "salami", "salsa", "sandwich", "sausage", "scone", 
            "seafood", "shrimp", "snack", "sorbet", "soy_sauce", "spaghetti", "spinach", "sprouts", "squash", 
            "steak", "stew", "strawberry", "string_cheese", "sundae", "sushi", "sweet_potato", "syrup", "taco", 
            "tamale", "tangerine", "tiramisu", "toast", "tofu", "tomato", "truffle", "tuna", "turkey", "vegetable", 
            "wafer", "waffle", "walnut", "watermelon", "whipped_cream", "yogurt", "zucchini", 'branch','birthday_cake',
            'cake_mix', 'coffee_bean', 'dogfood', 'donut', 'bush', 'thorn',"straw",
            'drink', 'fast_food','green_beans','leaf', 'batter','eclair','appetizer',"shell3",

            "bamboo",  "bark",   "beer",  "bonsai",  "bouquet",  "bread",  "breadstick",  "breakfast",  "cabbage",
        "cactus",  "calzone",  "cantaloupe",  "casserole",  "cereal",  "champagne",  "chips",   "christmas_tree",  "cigar",
        "cigarette",  "cigarette_butt",  "cilantro",  "cinnamon",  "clove",   "clover",  "cocktail",  "coleslaw",  "compost",
        "cordon_bleu",  "cork",   "corn",  "cornbread",  "cornhusk",  "cornmeal",  "cornucopia",  "cotton_candy",  "cracker",
        "crouton",  "crumb",  "daisy",  "dandelion",  "dessert",  "dip",   "eggshell",  "enchilada",  "espresso",  "fern",
        "firewood",  "flower",  "fungus",  "gourd",  "grain",  "granola",  "grapevine",  "grass",  "gravy",  "grits",
        "gum",   "gumball",  "gumdrop",  "gyro",   "ham",  "hash",   "hay",  "hedge",  "honeycomb",  "hummus",  "ice",
        "ice-cream_cone",  "ice_cube",  "ivy",  "jalapeno",  "lamb_chop",  "latte",  "lavender",  "log",   "lollipop",
        "margarita",  "marijuana",  "marmalade",  "mistletoe",  "mold2",   "mulberry",  "mulch",  "mustard",  "oil", 
        "orange_rind",  "orchid",  "palm_tree",  "pancake",  "patty",   "pea",  "peanut_butter",  "pepper1",   "pepper2", 
        "peppermint",  "pesto",  "pet_food",  "petal",  "pickle",  "piecrust",  "pill",   "pine_needle",  "pine_tree",
        "pineapple",  "pinecone",  "pistachio",  "pita",  "plant",  "poinsettia",  "poppy",  "potpie",  "prune",  "punch1", 
        "quesadilla",  "ready_meal",  "rhubarb",  "roll",   "root",  "rose",  "saffron",  "sardine",   "sauce",  "sauerkraut",
        "scallion",  "scallop",  "scrambled_egg",  "seaweed",  "seed",  "shell3",  "shortbread",  "smoothie",  "soda",
        "souffle",  "soup",  "spam",  "spareribs",  "star_fruit",  "stem",   "stir_fry",  "stuffing",  "stump",  "sugar_cube",
        "sunflower",  "taffy",  "tea",  "teabag",  "tomato_sauce",  "tortellini",  "tortilla",  "tostada",  "tree",  "tree_trunk",
        "tulip",  "tumbleweed",  "turf",   "wedding_cake",  "weed",  "wheat",  "wine",  "wrap",   "yolk" , "moss",  "parfait",
        "pudding",  "spring_roll",      "straw1",  "twig",
        ],

        "vehicles": [
            'airbag',"airboat", "aircraft_carrier", "airplane", "ambulance", "anchor", "bicycle", "boat", "bus", "canoe", "car", 
            "carriage", "cart", "dirt_bike", "ferry", "golf_cart", "go-kart", "helicopter", "hovercraft", "jeep", 
            "jetski", "kayak", "limousine", "minivan", "motorcycle", "police_car", "rickshaw", "sailboat", 
            "school_bus", "scooter", "ship", "skateboard", "sled", "snowmobile", "spacesuit", "submarine", "taxi", 
            "tractor", "train", "tricycle", "trolley", "truck", "van", "wagon", "yacht", 'buggy','catapult','bike',
            'car_door','car_seat', "station_wagon", "train_car","scooter",


            "blimp",  "bobsled",  "bulldozer",  "bumper",   "camper",  "cement_mixer",  "chariot",  "cruise_ship",  "dashboard",
            "engine",   "exhaust_pipe",   "ferris_wheel",   "firetruck",  "forklift",  "garbage_truck",  "gearshift",   "gondola",
            "grille",   "handbrake",  "handlebar",   "headlight",   "hearse",  "hot-air_balloon",  "hubcap",   "humvee",
            "jet",  "license_plate",   "lifesaver",   "mast",   "odometer",  "pedal",  "porthole",  "propeller",  "quad",
            "raft",  "rearview_mirror",   "rim",  "roadsweeper",  "rocket",  "roller_coaster",  "roof_rack",   "rudder", 
            "sail",   "satellite",  "seaplane",  "seatbelt",   "shopping_cart",  "sidecar",  "ski_lift",  "snowplow",  "space_shuttle",
            "speedboat",  "station_wagon",  "steamroller",  "steering_wheel",   "stroller",  "subway",   "sunroof",   "taillight", 
            "tank1",   "trailer",  "train_car",  "tugboat",  "unicycle",  "walker1",   "wheel",   "wheelbarrow",  "wheelchair",
            "windshield",  "windshield_wiper",  "wing" ,  "wreck" ,  "paddle",  "buoy",

        ],
        # "buildings": [
        #     "altar", "aquarium", "bank", "birdbath", "birdcage", "birdhouse", "cathedral", "church", 
        #     "garage", "gazebo", "greenhouse", "hospital", "hotel", "house", "hut", "igloo", 
        #     "igloo", "lighthouse", "mansion", "monastery", "mosque", "office", "pagoda", "pavilion", "prison", 
        #     "pyramid", "school", "shack", "shed", "skyscraper", "stable", "stage", "station", "store", 
        #     "synagogue", "temple", "tent", "theater", "tower", "train_station", "windmill", "zoo", 'ballot_box',
        #     'doghouse', 'carousel','arch','gate','revolving_door','antenna', 'awning',


        #     "backdrop",  "brick",  "chimney",  "column",   "coop",   "curb",  "duct",   "dumbwaiter",  "fence",  "fencepost",
        #     "fire_hydrant",  "flagpole",  "gallows",  "gargoyle",   "gravestone",  "guardrail",  "gutter",   "hydrant",  "lamppost",
        #     "mailbox",  "manhole",  "parking_meter",  "payphone",   "phone_booth",  "photo_booth",  "power_line",   "railing",
        #     "ramp",  "riser",   "road_sign",  "scaffold",  "scaffolding",  "stair",  "streetlight",  "swimming_pool",  "teepee",
        #     "telephone_pole",  "totem_pole",  "traffic_light",  "trapdoor",  "turnstile",  "wall",   "water_fountain",   "waterwheel", 
        #     "weather_vane" ,  "windsock"  ,"solar_panel",   "cash_machine",   "cash_register",  "flag",
        #     "boulder",   "chute",    "cloud",   "crane",  "cross",   "crystal1",   "graffiti",   "granite",   "gravel",   "hole", 
        #     "icicle",   "lava",  "snowball",   "hail",  "mud",   "pothole",  "puddle",   "rock",   "rust",   "sand",   "sewage",
        #     "slot",  "snow",  "stalagmite",   "wood"

        # ],
        "tools": [
            "abacus", "air_pump", "anvil", "axe", "backhoe", "barometer", "binoculars", "blender", 
            "blowtorch", "bolt", "brake", "calculator", "camcorder", "camera", "can_opener", "candle", "chainsaw", 
            "chisel", "cleaver", "clipboard", "compass", "crowbar", "dagger", "drill", "dynamite", "fire_extinguisher", 
            "fishing_pole", "flashlight", "funnel", "gear", "hammer", "hoe", "jackhammer", "knife", "ladder", 
            "lawnmower", "level", "lock", "mallet", "machete", "microscope", "nail", "needle", "nutcracker", 
            "paintbrush", "palette", "peg", "pickax", "pliers", "plunger", "rake", "saw", "scissors", 
            "screwdriver", "shovel", "sickle", "soldering_iron", "spatula", "stapler", "stethoscope", "tongs", 
            "toolbox", "torch", "trowel",  "vacuum", "wrench",  "bat2", "mouse2",'corkscrew', 
            'pocketknife',  'pump', 'screw', 'seesaw', 'sledgehammer','step_stool','tool', 
            'baton2','horn','eyepiece','arrow',"fishhook", "pipe1","pipe2","shell1","straw2",

            "backscratcher",  "barbed_wire",  "bazooka",  "blowgun",  "blower",   "board",   "bomb",
        "bow2",   "breathalyzer",  "brush",   "bubble_wrap",   "bullet",  "cable",  "camera1",  "camera2",
        "camera_lens",  "cane",   "cannon",  "cannonball",  "canvas",   "cardboard",   "centrifuge",  "chain",  "chalk",  
        "charcoal",   "coal",   "chicken_wire",  "chip",    "chopsticks",     "cigarette_holder",  "clay",   
        "clipper1",   "comb",   "combination_lock",  "cookie_cutter",  "crank",  "crayon",   "crossbow",
        "crutch",  "curling_iron",  "defibrillator",  "detonator",  "dolly",   "duct_tape",  "duster",   "dustpan", 
        "easel",   "eggbeater",  "eraser",  "extinguisher",   "eyedropper",  "file1",   "filter",  "first-aid_kit",
        "flamethrower",  "flashbulb",  "flatiron",   "flypaper",  "flyswatter",  "fork",   "fountain_pen",  "fuse",
        "gauge",  "gauze",  "gavel",  "generator",  "glue",  "grater",   "grenade",  "grinder",  "guillotine",  "gun",
        "gurney",  "gyroscope",  "hairbrush",  "hairdryer",  "handcuff",  "handle",   "hatchet",  "highlighter", 
        "hinge",   "hook1",   "hook2",   "hourglass",  "horseshoe",   "hose",   "ice_pack",   "icepick",  "incubator",
        "inhaler",   "ink",  "iron",   "jack",   "key",  "knitting_needle",  "ladle",   "landmine",  "laser_pointer",
        "latch",   "leash",   "lens",   "letter_opener",  "lighter",   "loom",   "lumber",   "machine_gun",  "magnet",
        "magnifier",  "magnifying_glass",  "marker",   "match",   "measuring_cup",  "metal_detector",  "meat_grinder",
        "missile",  "mold1",   "mop",   "mousetrap",  "mouthpiece",  "nail_clippers",  "nail_file",  "net", 
        "noose",  "oar",   "oilcan",  "pallet",   "parachute",  "peeler",  "pen",   "pencil",  "pencil_sharpener",
        "pepper_mill",  "pin",   "pincushion",   "pipe1",   "pipe2",   "pitchfork", "plaster_cast", "plastic_film", 
        "poker",  "pole",  "polisher",  "pulley", "punch2",  "quill",  "ratchet", "razor", "razor_blade",
        "reel", "revolver", "rifle", "rolling_pin",  "rope", "ruler",  "saddle",  "safety_pin", "sandbag",
        "sandpaper", "sawhorse", "scalpel",  "scarecrow",  "scoop",  "scraper", "scuba",  "sewing_kit",
        "sewing_machine", "shears",  "sheath",  "shield",  "shoehorn", "sifter",  "skewer",  "slicer", "sling", 
        "snorkel", "spark_plug", "spear",  "sponge",  "spool",  "spoon",  "sprinkler",  "squeegee", 
        "stake",  "stamp2",  "staple_gun", "stick",  "stirrup", "straightjacket",  "strainer",  "straw2",
        "stretcher",  "swab",  "sweeper", "swizzle_stick", "sword",  "syringe",  "tack",  "tackle",  "tape", 
        "tape_measure", "tarp", "thimble", "thread",  "thumbtack", "toothpick", "torpedo",  "trap", 
        "trident",  "trigger",  "tripod", "trunk",  "turbine",  "tweezers", "valve", "velcro",  "vise",
        "washboard", "watering_can", "wedge",  "whip", "whisk",  "wire",  "wire_cutters", "yarn",  "yoke" , "pendulum",
        "periscope", "petri_dish", "polygraph", "prism", "radar", "rain_gauge", "scale",  "seismograph", "siren",
        "sonogram", "speedometer", "stopwatch", "sundial", "telegraph", "telescope",
        "test_tube", "thermometer", "timer", "viewfinder",  "gel",  "sim_card",  "bungee", "cap",  "strap", 
        "coil", "gasket", "padlock", "penlight",    "roller",
        ],


        "body_parts_and_apparel": [
            "apron", "armor", "bandanna", "bathing_suit", "beanie", "belt", "blazer", "blouse", "boot", "bra", 
            "bracelet", "cape", "cardigan", "cloak", "coat", "crown", "diaper", "dress", "earring", "glasses", 
            "glove", "gown", "hat", "headband", "helmet", "hood", "jacket", "jeans", "jersey", "kilt", 
            "kimono", "leggings", "lingerie", "mittens", "necklace", "nightshirt", "overalls", "pajamas", "panties", 
            "pants", "raincoat", "robe", "scarf", "shirt", "shoe", "shorts", "skirt", "slippers", 
            "socks", "stockings", "suit", "suspenders", "sweater", "swimsuit", "t-shirt", "tie", "turban", 
            "tuxedo", "undershirt", "underwear", "vest", "watch",  'bag','belt_buckle','bowler_hat',
            'boxing_gloves','bracelet1','bracelet2', 'brass_knuckles', 'brace','fishnet_stockings', 'footbath',
            'earplug','footrest', 
             # "body_parts": [ # these are concatenated because most items here have body parts in them
            "ankle", "arm", "beard", "belly", "brain", "cheek", "chest", "chin", "ear", "elbow", "eye", 
            "eyebrow", "eyelash", "face", "finger", "foot", "hair", "hand", "head", "hip", "jaw", "knee", 
            "leg", "lip", "mouth", "mullet", "neck", "nose", "shoulder", "skin", "stomach", "thumb", "toe", "tongue", 
            "tooth", "wrist", 'braid', 'footprint','eyeliner','baby','anklet','amber', "chest1",

## Part II
            "backpack", "badge", "bandage",  "barrette", "bib", "bikini", "blinder", "blindfold",
            "boa", "bolo_tie", "bone",  "bonnet", "bow1", "bow3",  "bowtie", "boxer_shorts", "briefcase",  
            "brooch", "buckle",  "bulletproof_vest", "button1",  "calf2",  "chaps", "chest1",  "clasp", 
            "cleat",  "clothes", "collar",  "contact_lens", "corsage", "corset", "costume", "coverall",
            "cufflink", "cummerbund", "denture",  "duffel_bag",  "eye_patch", "face_mask",  "feather", 
            "flip_flop", "flipper",  "football_helmet", "fur_coat", "garter", "gas_mask", "goggles",
            "hairnet", "hairpin", "handkerchief", "harness",  "headdress", "headlamp",  "headphones",
            "headscarf", "headset", "hearing_aid", "holster", "hoodie", "insole",  "jewelry", "jumpsuit",
            "kneepad", "lab_coat", "lanyard", "leotard", "life_jacket", "locket", "loincloth", "luggage", 
            "mask",  "medal",  "mitten", "moccasin", "muff",  "mustache", "navel", "outfit", "pantsuit",
            "pantyhose", "patch", "pocket",  "pocket_watch",  "polo_shirt", "purse", "retainer",  "ring", 
            "rosary",  "sandal", "shawl", "shoelace", "shower_cap", "ski_boots", "skull",  "slipper",
            "snowshoe", "snowsuit", "sock", "sombrero", "spur",  "stiletto",  "straightjacket",  "suitcase", 
            "sunglasses", "sweatsuit", "tag",  "tattoo", "tiara", "toga", "top_hat", "torso",
            "tube_top", "turtleneck", "umbrella",  "uniform", "veil", "visor",  "wallet", "wetsuit", "wig",
            "wooden_leg",  "zipper" , "snorkel",  "boy",  "crystal2",  "diamond",  "emerald", "fingerprint", 
            "girl",  "handprint" ,"jewel", "man",  "silicone", "splinter", "woman", "pearl", "pedometer",
            "ruby",  "skeleton",  
 
        ],
        # "instruments": [
        #     "accordion", "banjo", "bassoon", "bongo", "cello", "clarinet", "drum", "flute", "french_horn", 
        #     "guitar", "harmonica", "harp", "kazoo", "mandolin", "maracas", "metronome", "piano", "recorder", 
        #     "saxophone", "tambourine", "triangle", "trombone", "trumpet", "tuba", "ukulele", "violin", "xylophone",
        #     'bagpipe','baton1','drumstick','amplifier',"tuning_fork",


        #     "bell",   "chime",  "cymbal",  "gong",  "megaphone",  "microphone",  "organ",   "whistle",
        #     "wind_chimes",  "record",   "record_player",  "turntable",   "music_box",
        # ],
        "household_items_and_furniture": [
            "air_conditioner", "air_mattress", "armchair", "ashtray", "bathmat", "bathrobe", "bathtub", "bed", 
            "blanket", "blinds", "bookshelf", "broom", "bucket", "cabinet", "carpet", "chair", "clock", "coffee_table", 
            "couch", "crib", "curtain", "desk", "dresser", "fan", "faucet", "fireplace", "floor_lamp", 
            "freezer", "lamp", "lightbulb", "mattress", "mirror", "oven", "pillow", "refrigerator", "rug", 
            "shower", "sink", "sofa_bed", "stove", "table", "television", "toilet", "toaster", "towel", 
            "vacuum_cleaner", "washing_machine", "window", 'stool', 'beaker', 'beanbag', 'bedpan','bottle',
            'bottle_opener','bracket', 'food_processor', 'electric_chair','christmas_card','credit_card','door',
            'fire_alarm','chandelier','album','aluminum_foil','doorbell','doorhandle', 'doorknob', 'doorknocker',
            'doormat','doorstop',"aquarium", "barrel", "battery", "chest2","shell2",


            "banner", "basket", "bassinet", "bedpost", "bench", "bin", "binder",  "blind", 
            "book", "bookmark", "bowl", "box", "breadbox", "bulletin_board", "bunkbed", "burner",  "button2",  "cage",  "can", 
            "candelabra", "candlestick", "canister", "cassette",  "cd_player", "cellphone", "centerpiece", "chalkboard", "chest2",
            "chinaware", "clipper2",  "closet", "clothesline", "clothespin", "coaster",  "coat_rack",
            "coffee_filter", "coffee_pot", "coffeemaker", "coffin", "coin",  "computer", "computer_screen",
            "container", "cooker",  "cookie_sheet", "cooler",  "copier",  "corkboard", "cot",  "counter", 
            "crate", "cuckoo_clock", "cup", "cutting_board", "deodorant",  "dial",  "dish", "dishrag",
            "dishwasher", "dishwashing_liquid", "diskette",  "doily", "drain",  "drawer",  "dryer",  "dumpster",  "envelope",
            "file2",  "filing_cabinet", "film",  "fire_pit",  "flask",  "floss",  "folder",  "frame",  "furnace", 
            "garbage",  "glass",  "globe",  "goblet", "gramophone", "grate", "grill",  "hairspray", "hammock", "hanger", 
            "hard_disk",  "hatbox", "headrest",  "heater", "highchair", "honeypot", "hookah",  "hot-water_bottle",
            "hot_tub", "hotplate", "icemaker", "incense", "inkwell", "ironing_board", "jar", "jug",
            "juicer1",  "juicer2",  "jukebox", "keg",  "kettle", "keyboard",  "keyhole",  "knob",  "lampshade",
            "lantern", "laptop", "laundry_basket", "lectern", "lid",  "light_switch", "lip_balm",  "lip_gloss",  "lipstick", 
            "locker", "loveseat", "lunchbox", "mail",  "makeup",  "mannequin",  "mantle", "map",  "mascara", 
            "mat", "matchbox",  "memory_stick",  "microwave", "mixer",  "modem", "money", "mosquito_net", "motherboard", 
            "mousepad", "mug", "nail_polish",  "napkin", "napkin_ring", "nightstand", "notebook", "notepad", "ottoman",
            "outlet",  "painting",  "pan",  "paper",  "paper_bag", "paper_plate", "paper_towel", "paperclip",  "paperweight",
            "penholder", "pennant",  "perfume",  "phone",  "photograph", "pillbox",  "pitcher", "place_mat", "plate",
            "plug",  "polaroid",  "poster", "pot",  "potholder", "potpourri", "powder",  "printer", "projector", "pulpit",
            "quilt", "rack1",  "rack2",  "radiator", "radio", "rag",  "recliner", "red_carpet", "remote_control", "ribbon", 
            "rocking_chair", "router",  "rubber_band",  "saltshaker", "sarcophagus",  "satellite_dish",  "saucer",
            "scanner",  "screen1",  "screen2",  "shaker",  "shaving_cream",  "sheet",  "shelf", "shell1", "shell2",
            "shoe_polish", "shopping_basket", "shower_curtain", "showerhead", "shredder", "shutter",  "sleeping_bag", 
            "smoke_alarm", "soap",  "soda_fountain",  "speaker",  "sponge",  "spout",  "stained_glass",  "stamp1",
            "staple",  "statue",  "stereo", "sticker",  "stove1",  "stove2",  "switch",  "tab",  "tablecloth", "tablet", 
            "tank2",  "tape_recorder", "tapestry", "teacup", "teapot", "terrarium", "thermos", "thermostat", "throne",
            "tile",  "toaster_oven", "toilet_paper", "toothbrush", "toothpaste",  "touchpad",  "towel_rack", "trashcan",
            "tray", "trophy",  "trough",  "tupperware", "typewriter", "urinal",  "urn",  "vase", "vending_machine", "vent", 
            "vial",  "videocassette", "waffle_iron", "wallpaper", "washcloth", "water_bottle", "water_cooler", "water_filter", 
            "water_heater", "wax_paper", "webcam", "whiteboard", "wick",  "windowsill", "wine_bottle", "wine_cooler",  "wineglass",
            "wok",  "workbench", "wrapping_paper", "wreath",  "barcode", "crucifix",  "fire",  "foam", "gold",  "treasure",
            "wax",  "chalice", "charger", "checkbook", "cord", "cushion", "silverware",
        ],
        "toys_and_games": [
            "backgammon", "ball", "balloon", "barbie", "board_game", "blocks", "card", "checkers", "chess_piece", 
            "dice", "domino", "doll", "frisbee", "game", "hobbyhorse", "jigsaw_puzzle", "joystick", "kite", 
            "lego", "marble", "pinball", "playpen", "puppet", "rattle", "rocking_horse", "scrabble",  
            "slinky", "spinning_top", "squirt_gun", "stuffed_animal", "swing", "teddy_bear", "toy", "train_set", 
            "trampoline", "yo-yo", 'baseball', 'baseball_bat','baseball_glove', 'basketball','basketball_hoop',
            'baton4','baton3',"dollhouse", 


            "balance_beam", "barbell", "beachball", "block",  "boomerang", "bowling_ball", "chessboard",
            "comic_book", "confetti", "crystal_ball",  "dart",  "dartboard", "diving_board", "dreidel", "dumbbell",
            "easter_egg",  "exerciser",  "figurine", "firecracker", "fireworks", "float",  "football", "goalpost",
            "golf_club", "hockey_stick", "home_plate", "hopscotch",  "hula_hoop", "iceskate", "javelin",  "jump_rope",
            "kaleidoscope", "noisemaker", "origami",  "pacifier",  "piggy_bank", "ping-pong_table", "pinwheel", "playing_card",
            "pogo_stick", "pom-pom",  "pool_table", "puck",  "punching_bag", "racket",  "robot", "rollerblade", "rollerskate",
            "roulette_wheel", "sandbox", "sandcastle", "scoreboard", "shuffleboard", "ski", "ski_pole", "slide",  "slime", 
            "slingshot", "slot_machine", "snowboard", "snowman", "sparkler", "springboard",  "stilt", "surfboard", "swing_set",
            "target",  "tee", "tennis_ball", "ticktacktoe", "treadmill", "videogame", "volleyball", "walker2",  "wand", 
            "whoopee_cushion", "gift",  "tinsel",  "sequin", "bead" ,"bubble", "gem", "knitting", "knot", "paint",    "soccer_ball",

            "accordion", "banjo", "bassoon", "bongo", "cello", "clarinet", "drum", "flute", "french_horn", 
            "guitar", "harmonica", "harp", "kazoo", "mandolin", "maracas", "metronome", "piano", "recorder", 
            "saxophone", "tambourine", "triangle", "trombone", "trumpet", "tuba", "ukulele", "violin", "xylophone",
            'bagpipe','baton1','drumstick','amplifier',"tuning_fork",

            "bell",   "chime",  "cymbal",  "gong",  "megaphone",  "microphone",  "organ",   "whistle",
            "wind_chimes",  "record",   "record_player",  "turntable",   "music_box",
  
        ],
        # "body_parts": [
        #     "ankle", "arm", "beard", "belly", "brain", "cheek", "chest", "chin", "ear", "elbow", "eye", 
        #     "eyebrow", "eyelash", "face", "finger", "foot", "hair", "hand", "head", "hip", "jaw", "knee", 
        #     "leg", "lip", "mouth", "mullet", "neck", "nose", "shoulder", "skin", "stomach", "thumb", "toe", "tongue", 
        #     "tooth", "wrist", 'braid', 'footprint','eyeliner','baby','anklet'
        # ]
    }

    # Initializing category dictionary
    categories = defaultdict(list)

    for cat, words in word_lists.items():
        categories[cat].extend(words)

    df_categories_full = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in categories.items()]))

    return categories#, df_categories_full


def get_categories2():
    word_categories = {
    "animals": [
        "calf1",  "chick",  "chihuahua",  "cobra",  "cockatoo",  "cocoon",  "coral",
        "cougar",  "dalmatian",  "dragonfly",  "flamingo",  "fly",  "gopher",  "grasshopper",
        "ladybug",  "leech",  "lightning_bug",  "maggot",  "moth",  "mussel",  "nest",  "piglet",
        "poodle",  "praying_mantis",  "puffin",  "pug",  "racehorse",  "sea_urchin",  "seagull",  "seahorse",
        "spider_web",  "swordfish",  "tarantula",  "tick",  "toucan",  "vulture",  "warthog",  "fossil",
	    "buffet",

    ],
    "foods_plants": [  "bamboo",  "bark",   "beer",  "bonsai",  "bouquet",  "bread",  "breadstick",  "breakfast",  "cabbage",
        "cactus",  "calzone",  "cantaloupe",  "casserole",  "cereal",  "champagne",  "chips",   "christmas_tree",  "cigar",
        "cigarette",  "cigarette_butt",  "cilantro",  "cinnamon",  "clove",   "clover",  "cocktail",  "coleslaw",  "compost",
        "cordon_bleu",  "cork",   "corn",  "cornbread",  "cornhusk",  "cornmeal",  "cornucopia",  "cotton_candy",  "cracker",
        "crouton",  "crumb",  "daisy",  "dandelion",  "dessert",  "dip",   "eggshell",  "enchilada",  "espresso",  "fern",
        "firewood",  "flower",  "fungus",  "gourd",  "grain",  "granola",  "grapevine",  "grass",  "gravy",  "grits",
        "gum",   "gumball",  "gumdrop",  "gyro",   "ham",  "hash",   "hay",  "hedge",  "honeycomb",  "hummus",  "ice",
        "ice-cream_cone",  "ice_cube",  "ivy",  "jalapeno",  "lamb_chop",  "latte",  "lavender",  "log",   "lollipop",
        "margarita",  "marijuana",  "marmalade",  "mistletoe",  "mold2",   "mulberry",  "mulch",  "mustard",  "oil", 
        "orange_rind",  "orchid",  "palm_tree",  "pancake",  "patty",   "pea",  "peanut_butter",  "pepper1",   "pepper2", 
        "peppermint",  "pesto",  "pet_food",  "petal",  "pickle",  "piecrust",  "pill",   "pine_needle",  "pine_tree",
        "pineapple",  "pinecone",  "pistachio",  "pita",  "plant",  "poinsettia",  "poppy",  "potpie",  "prune",  "punch1", 
        "quesadilla",  "ready_meal",  "rhubarb",  "roll",   "root",  "rose",  "saffron",  "sardine",   "sauce",  "sauerkraut",
        "scallion",  "scallop",  "scrambled_egg",  "seaweed",  "seed",  "shell3",  "shortbread",  "smoothie",  "soda",
        "souffle",  "soup",  "spam",  "spareribs",  "star_fruit",  "stem",   "stir_fry",  "stuffing",  "stump",  "sugar_cube",
        "sunflower",  "taffy",  "tea",  "teabag",  "tomato_sauce",  "tortellini",  "tortilla",  "tostada",  "tree",  "tree_trunk",
        "tulip",  "tumbleweed",  "turf",   "wedding_cake",  "weed",  "wheat",  "wine",  "wrap",   "yolk" , "moss",  "parfait",
        "pudding",  "spring_roll",      "straw1",  "twig",
],
    "vehicles": [  "blimp",  "bobsled",  "bulldozer",  "bumper",   "camper",  "cement_mixer",  "chariot",  "cruise_ship",  "dashboard",
        "engine",   "exhaust_pipe",   "ferris_wheel",   "firetruck",  "forklift",  "garbage_truck",  "gearshift",   "gondola",
        "grille",   "handbrake",  "handlebar",   "headlight",   "hearse",  "hot-air_balloon",  "hubcap",   "humvee",
        "jet",  "license_plate",   "lifesaver",   "mast",   "odometer",  "pedal",  "porthole",  "propeller",  "quad",
        "raft",  "rearview_mirror",   "rim",  "roadsweeper",  "rocket",  "roller_coaster",  "roof_rack",   "rudder", 
        "sail",   "satellite",  "seaplane",  "seatbelt",   "shopping_cart",  "sidecar",  "ski_lift",  "snowplow",  "space_shuttle",
        "speedboat",  "station_wagon",  "steamroller",  "steering_wheel",   "stroller",  "subway",   "sunroof",   "taillight", 
        "tank1",   "trailer",  "train_car",  "tugboat",  "unicycle",  "walker1",   "wheel",   "wheelbarrow",  "wheelchair",
        "windshield",  "windshield_wiper",  "wing" ,  "wreck" ,  "paddle",  "buoy"
    ],
    "buildings": [  "backdrop",  "brick",  "chimney",  "column",   "coop",   "curb",  "duct",   "dumbwaiter",  "fence",  "fencepost",
        "fire_hydrant",  "flagpole",  "gallows",  "gargoyle",   "gravestone",  "guardrail",  "gutter",   "hydrant",  "lamppost",
        "mailbox",  "manhole",  "parking_meter",  "payphone",   "phone_booth",  "photo_booth",  "power_line",   "railing",
        "ramp",  "riser",   "road_sign",  "scaffold",  "scaffolding",  "stair",  "streetlight",  "swimming_pool",  "teepee",
        "telephone_pole",  "totem_pole",  "traffic_light",  "trapdoor",  "turnstile",  "wall",   "water_fountain",   "waterwheel", 
        "weather_vane" ,  "windsock"  ,"solar_panel",   "cash_machine",   "cash_register",  "flag",
        "boulder",   "chute",    "cloud",   "crane",  "cross",   "crystal1",   "graffiti",   "granite",   "gravel",   "hole", 
        "icicle",   "lava",  "snowball",   "hail",  "mud",   "pothole",  "puddle",   "rock",   "rust",   "sand",   "sewage",
        "slot",  "snow",  "stalagmite",   "wood"
    ],
    "instruments": [  "bell",   "chime",  "cymbal",  "gong",  "megaphone",  "microphone",  "organ",   "whistle",
        "wind_chimes",  "record",   "record_player",  "turntable",   "music_box",
    ],
    "tools": [  "backscratcher",  "barbed_wire",  "bazooka",  "blowgun",  "blower",   "board",   "bomb",
        "bow2",   "breathalyzer",  "brush",   "bubble_wrap",   "bullet",  "cable",  "camera1",  "camera2",
        "camera_lens",  "cane",   "cannon",  "cannonball",  "canvas",   "cardboard",   "centrifuge",  "chain",  "chalk",  
        "charcoal",   "coal",   "chicken_wire",  "chip",    "chopsticks",     "cigarette_holder",  "clay",   
        "clipper1",   "comb",   "combination_lock",  "cookie_cutter",  "crank",  "crayon",   "crossbow",
        "crutch",  "curling_iron",  "defibrillator",  "detonator",  "dolly",   "duct_tape",  "duster",   "dustpan", 
        "easel",   "eggbeater",  "eraser",  "extinguisher",   "eyedropper",  "file1",   "filter",  "first-aid_kit",
        "flamethrower",  "flashbulb",  "flatiron",   "flypaper",  "flyswatter",  "fork",   "fountain_pen",  "fuse",
        "gauge",  "gauze",  "gavel",  "generator",  "glue",  "grater",   "grenade",  "grinder",  "guillotine",  "gun",
        "gurney",  "gyroscope",  "hairbrush",  "hairdryer",  "handcuff",  "handle",   "hatchet",  "highlighter", 
        "hinge",   "hook1",   "hook2",   "hourglass",  "horseshoe",   "hose",   "ice_pack",   "icepick",  "incubator",
        "inhaler",   "ink",  "iron",   "jack",   "key",  "knitting_needle",  "ladle",   "landmine",  "laser_pointer",
        "latch",   "leash",   "lens",   "letter_opener",  "lighter",   "loom",   "lumber",   "machine_gun",  "magnet",
        "magnifier",  "magnifying_glass",  "marker",   "match",   "measuring_cup",  "metal_detector",  "meat_grinder",
        "missile",  "mold1",   "mop",   "mousetrap",  "mouthpiece",  "nail_clippers",  "nail_file",  "net", 
        "noose",  "oar",   "oilcan",  "pallet",   "parachute",  "peeler",  "pen",   "pencil",  "pencil_sharpener",
        "pepper_mill",  "pin",   "pincushion",   "pipe1",   "pipe2",   "pitchfork", "plaster_cast", "plastic_film", 
        "poker",  "pole",  "polisher",  "pulley", "punch2",  "quill",  "ratchet", "razor", "razor_blade",
        "reel", "revolver", "rifle", "rolling_pin",  "rope", "ruler",  "saddle",  "safety_pin", "sandbag",
        "sandpaper", "sawhorse", "scalpel",  "scarecrow",  "scoop",  "scraper", "scuba",  "sewing_kit",
        "sewing_machine", "shears",  "sheath",  "shield",  "shoehorn", "sifter",  "skewer",  "slicer", "sling", 
        "snorkel", "spark_plug", "spear",  "sponge",  "spool",  "spoon",  "sprinkler",  "squeegee", 
        "stake",  "stamp2",  "staple_gun", "stick",  "stirrup", "straightjacket",  "strainer",  "straw2",
        "stretcher",  "swab",  "sweeper", "swizzle_stick", "sword",  "syringe",  "tack",  "tackle",  "tape", 
        "tape_measure", "tarp", "thimble", "thread",  "thumbtack", "toothpick", "torpedo",  "trap", 
        "trident",  "trigger",  "tripod", "trunk",  "turbine",  "tweezers", "valve", "velcro",  "vise",
        "washboard", "watering_can", "wedge",  "whip", "whisk",  "wire",  "wire_cutters", "yarn",  "yoke"  "pendulum",
        "periscope", "petri_dish", "polygraph", "prism", "radar", "rain_gauge", "scale",  "seismograph", "siren",
        "sonogram", # Medical imaging output/device "speedometer", "stopwatch", "sundial", "telegraph", "telescope",
        "test_tube", "thermometer", "timer", "viewfinder",  "gel",  "sim_card",  "bungee", "cap",  "strap", 
        "coil", "gasket", "padlock", "penlight",    "roller",
],
    "household_items_and_furniture": [ "banner", "basket", "bassinet", "bedpost", "bench", "bin", "binder",  "blind", 
        "book", "bookmark", "bowl", "box", "breadbox", "bulletin_board", "bunkbed", "burner",  "button2",  "cage",  "can", 
        "candelabra", "candlestick", "canister", "cassette",  "cd_player", "cellphone", "centerpiece", "chalkboard", "chest2",
        "chinaware", "clipper2",  "closet", "clothesline", "clothespin", "coaster",  "coat_rack",
        "coffee_filter", "coffee_pot", "coffeemaker", "coffin", "coin",  "computer", "computer_screen",
        "container", "cooker",  "cookie_sheet", "cooler",  "copier",  "corkboard", "cot",  "counter", 
        "crate", "cuckoo_clock", "cup", "cutting_board", "deodorant",  "dial",  "dish", "dishrag",
        "dishwasher", "dishwashing_liquid", "diskette",  "doily", "drain",  "drawer",  "dryer",  "dumpster",  "envelope",
        "file2",  "filing_cabinet", "film",  "fire_pit",  "flask",  "floss",  "folder",  "frame",  "furnace", 
        "garbage",  "glass",  "globe",  "goblet", "gramophone", "grate", "grill",  "hairspray", "hammock", "hanger", 
        "hard_disk",  "hatbox", "headrest",  "heater", "highchair", "honeypot", "hookah",  "hot-water_bottle",
        "hot_tub", "hotplate", "icemaker", "incense", "inkwell", "ironing_board", "jar", "jug",
        "juicer1",  "juicer2",  "jukebox", "keg",  "kettle", "keyboard",  "keyhole",  "knob",  "lampshade",
        "lantern", "laptop", "laundry_basket", "lectern", "lid",  "light_switch", "lip_balm",  "lip_gloss",  "lipstick", 
        "locker", "loveseat", "lunchbox", "mail",  "makeup",  "mannequin",  "mantle", "map",  "mascara", 
        "mat", "matchbox",  "memory_stick",  "microwave", "mixer",  "modem", "money", "mosquito_net", "motherboard", 
        "mousepad", "mug", "nail_polish",  "napkin", "napkin_ring", "nightstand", "notebook", "notepad", "ottoman",
        "outlet",  "painting",  "pan",  "paper",  "paper_bag", "paper_plate", "paper_towel", "paperclip",  "paperweight",
        "penholder", "pennant",  "perfume",  "phone",  "photograph", "pillbox",  "pitcher", "place_mat", "plate",
        "plug",  "polaroid",  "poster", "pot",  "potholder", "potpourri", "powder",  "printer", "projector", "pulpit",
        "quilt", "rack1",  "rack2",  "radiator", "radio", "rag",  "recliner", "red_carpet", "remote_control", "ribbon", 
        "rocking_chair", "router",  "rubber_band",  "saltshaker", "sarcophagus",  "satellite_dish",  "saucer",
        "scanner",  "screen1",  "screen2",  "shaker",  "shaving_cream",  "sheet",  "shelf", "shell1", "shell2",
        "shoe_polish", "shopping_basket", "shower_curtain", "showerhead", "shredder", "shutter",  "sleeping_bag", 
        "smoke_alarm", "soap",  "soda_fountain",  "speaker",  "sponge",  "spout",  "stained_glass",  "stamp1",
        "staple",  "statue",  "stereo", "sticker",  "stove1",  "stove2",  "switch",  "tab",  "tablecloth", "tablet", 
        "tank2",  "tape_recorder", "tapestry", "teacup", "teapot", "terrarium", "thermos", "thermostat", "throne",
        "tile",  "toaster_oven", "toilet_paper", "toothbrush", "toothpaste",  "touchpad",  "towel_rack", "trashcan",
        "tray", "trophy",  "trough",  "tupperware", "typewriter", "urinal",  "urn",  "vase", "vending_machine", "vent", 
        "vial",  "videocassette", "waffle_iron", "wallpaper", "washcloth", "water_bottle", "water_cooler", "water_filter", 
        "water_heater", "wax_paper", "webcam", "whiteboard", "wick",  "windowsill", "wine_bottle", "wine_cooler",  "wineglass",
        "wok",  "workbench", "wrapping_paper", "wreath"  "barcode" ,"crucifix",  "fire",  "foam", "gold",  "treasure",
        "wax",  "chalice", "charger", "checkbook", "cord", "cushion", "silverware",
    ],
    "toys_and_games": [ "balance_beam", "barbell", "beachball", "block",  "boomerang", "bowling_ball", "chessboard",
        "comic_book", "confetti", "crystal_ball",  "dart",  "dartboard", "diving_board", "dreidel", "dumbbell",
        "easter_egg",  "exerciser",  "figurine", "firecracker", "fireworks", "float",  "football", "goalpost",
        "golf_club", "hockey_stick", "home_plate", "hopscotch",  "hula_hoop", "iceskate", "javelin",  "jump_rope",
        "kaleidoscope", "noisemaker", "origami",  "pacifier",  "piggy_bank", "ping-pong_table", "pinwheel", "playing_card",
        "pogo_stick", "pom-pom",  "pool_table", "puck",  "punching_bag", "racket",  "robot", "rollerblade", "rollerskate",
        "roulette_wheel", "sandbox", "sandcastle", "scoreboard", "shuffleboard", "ski", "ski_pole", "slide",  "slime", 
        "slingshot", "slot_machine", "snowboard", "snowman", "sparkler", "springboard",  "stilt", "surfboard", "swing_set",
        "target",  "tee", "tennis_ball", "ticktacktoe", "treadmill", "videogame", "volleyball", "walker2",  "wand", 
        "whoopee_cushion" ,"gift",  "tinsel",  "sequin", "bead" ,"bubble", "gem", "knitting", "knot", "paint",    "soccer_ball",
 ],
    "body_parts_and_apparel": [ "backpack", "badge", "bandage",  "barrette", "bib", "bikini", "blinder", "blindfold",
        "boa", "bolo_tie", "bone",  "bonnet", "bow1", "bow3",  "bowtie", "boxer_shorts", "briefcase",  
        "brooch", "buckle",  "bulletproof_vest", "button1",  "calf2",  "chaps", "chest1",  "clasp", 
        "cleat",  "clothes", "collar",  "contact_lens", "corsage", "corset", "costume", "coverall",
        "cufflink", "cummerbund", "denture",  "duffel_bag",  "eye_patch", "face_mask",  "feather", 
        "flip_flop", "flipper",  "football_helmet", "fur_coat", "garter", "gas_mask", "goggles",
        "hairnet", "hairpin", "handkerchief", "harness",  "headdress", "headlamp",  "headphones",
        "headscarf", "headset", "hearing_aid", "holster", "hoodie", "insole",  "jewelry", "jumpsuit",
        "kneepad", "lab_coat", "lanyard", "leotard", "life_jacket", "locket", "loincloth", "luggage", 
        "mask",  "medal",  "mitten", "moccasin", "muff",  "mustache", "navel", "outfit", "pantsuit",
        "pantyhose", "patch", "pocket",  "pocket_watch",  "polo_shirt", "purse", "retainer",  "ring", 
        "rosary",  "sandal", "shawl", "shoelace", "shower_cap", "ski_boots", "skull",  "slipper",
        "snowshoe", "snowsuit", "sock", "sombrero", "spur",  "stiletto",  "straightjacket",  "suitcase", 
        "sunglasses", "sweatsuit", "tag",  "tattoo", "tiara", "toga", "top_hat", "torso",
        "tube_top", "turtleneck", "umbrella",  "uniform", "veil", "visor",  "wallet", "wetsuit", "wig",
        "wooden_leg",  "zipper" , "snorkel",  "boy",  "crystal2",  "diamond",  "emerald", "fingerprint", 
        "girl",  "handprint,jewel", "man",  "silicone", "splinter", "woman", "pearl", "pedometer",
        "ruby",  "skeleton",  
 ]
}   

    return word_categories